runtime: go123

handlers:
  - url: /static/(.*\.(png|jpg|ico|otf|woff|woff2))$
    static_files: static/\1
    upload: static/.*\.(png|jpg|ico|otf|woff|woff2)$
    secure: always

  - url: /(.*\.(css|js))$
    static_files: web/\1
    upload: web/.*\.(css|js)$
    secure: always

  - url: /.*
    script: auto
    secure: always